### PR TITLE
Update options.md

### PR DESCRIPTION
**Pull request by debuggingfuture**
let's use this pr for review

### CODE REVIEW

**Comment by cherrry** [comment]
:ok_hand: ok you win

**Comment by debuggingfuture** [comment]
notes on option
https://github.com/onesky/knowledge-base/blob/master/scala/error_handling.md#option

**Comment by debuggingfuture** [comment]
before mentioning Missing value, I would suggest elaborate the motivation of Option a little bit more, so people understand this is for legacy only  "Suppose you have a method that may either return some value or null if the value doesn't exist,"
which Programming in Scala ch3 is a good ref

**Comment by jacquetwong** [comment]
lgtm :+1:

**Pull request merged**
